version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20 # ESLint와 Vite 8 요구사항에 맞춰 18에서 20으로 업그레이드
    commands:
      - echo Installing source dependencies...
      - cd walking-library
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Building the React application...
      - npm run build # 이미 walking-library 폴더 안이므로 cd 없이 바로 실행

artifacts:
  files:
    - '**/*'
  base-directory: walking-library/dist
